# Generated by Django 3.2.7 on 2022-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=100)),
                ('diseasename', models.CharField(max_length=20)),
                ('explane', models.TextField()),
                ('symptomdata', models.CharField(max_length=50)),
                ('prevent', models.CharField(max_length=50)),
                ('danger', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IcdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=50)),
                ('symptom', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
                ('symptomexplane', models.CharField(max_length=200)),
                ('symptomdata', models.CharField(max_length=50)),
                ('symptomprevent', models.CharField(max_length=50)),
                ('symptomdanger', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indata', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
                ('embedding', models.TextField()),
                ('choose_icd', models.ManyToManyField(to='chatbots.IcdData')),
            ],
        ),
    ]
