# Generated by Django 3.2.7 on 2022-10-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=100)),
                ('diseasename', models.CharField(max_length=20)),
                ('explane', models.TextField()),
                ('symptomdata', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=50)),
                ('symptom', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indata', models.CharField(max_length=100)),
                ('symptom', models.TextField()),
                ('embedding', models.TextField()),
            ],
        ),
    ]
