# Generated by Django 3.2.7 on 2022-11-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_symptomdata_symptomexplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotNama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
