# Generated by Django 3.2.7 on 2022-11-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_notnama'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotNama',
            new_name='NotName',
        ),
    ]
