# Generated by Django 3.2.7 on 2022-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_rename_notnama_notname'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICD', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='symptomtable',
            name='choose_icd',
            field=models.ManyToManyField(to='chatbots.IcdData'),
        ),
    ]
