pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                dir("front") {
                    sh 'if (sudo docker ps | grep "nextcontainer"); then sudo docker stop nextcontainer; fi'
                    sh 'sudo docker build -t nextimage .'
                }
            }
        }
        stage('deploy') {
            steps {
                sh 'sudo docker run -it -d --rm -p 3000:3000 --name nextcontainer nextimage'
            }
        }
    }
}